wip: can we put clippy in this action?

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -2,7 +2,7 @@ name: Rust
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "dev" ]
   pull_request:
     branches: [ "main" ]
 
@@ -20,3 +20,14 @@ jobs:
       run: cargo build --verbose
     - name: Run tests
       run: cargo test --verbose
+
+    - name: Check for Clippy Warnings
+      run: |
+        # Run Clippy and capture its output
+        CLIPPY_OUTPUT=$(cargo clippy --message-format json)
+
+        # Check if Clippy produced any warnings
+        if echo "$CLIPPY_OUTPUT" | jq -e '.reason | contains("warning")' > /dev/null; then
+          echo "Clippy warnings found. This pull request will be denied."
+          exit 1  # Set the workflow status to failed
+        fi
